{% set name = "resmda" %}
{% set version = "1.0.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/dageo-{{ version }}.tar.gz
  sha256: 387ef40e74a4267034620cdc65cb04117c677e75cfec51cef23134f2187893fd

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python {{ python_min }}
    - setuptools
    - setuptools-scm
  run:
    - python >={{ python_min }}
    - numpy
    - scipy
    - scooby

test:
  imports:
    - dageo
  commands:
    - pip check
  requires:
    - python {{ python_min }}
    - pip

about:
  home: https://github.com/tuda-geo/dageo
  summary: Data Assimilation in Geosciences.
  license: Apache-2.0
  license_family: APACHE
  license_file: LICENSE
  doc_url: https://tuda-geo.github.io/dageo/

extra:
  recipe-maintainers:
    - prisae
    - gabrielserrao
