{% set name = "resmda" %}
{% set version = "1.0.0" %}
{% set python_min = "3.10" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/resmda-{{ version }}.tar.gz
  sha256: 2d2c60de07aec8f0ad25a76750f9ba0e65cf530f03143c140b01542de5e3c173

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python {{ python_min }}
    - setuptools
    - setuptools-scm
  run:
    - python >={{ python_min }}
    - numpy
    - scipy
    - scooby

test:
  imports:
    - resmda
  commands:
    - pip check
  requires:
    - python {{ python_min }}
    - pip

about:
  home: https://github.com/tuda-geo/resmda
  summary: A simple 2D reservoir modeller plus ESMDA.
  license: Apache-2.0
  license_family: APACHE
  license_file: LICENSE
  doc_url: https://tuda-geo.github.io/resmda/

extra:
  recipe-maintainers:
    - prisae
    - gabrielserrao
